// "Wer kann Sonntag?" – Nachrichten in der Mannschaftsgruppe.
// Jede Liste ist in beiden Sprachen gleich lang, damit der Zufall gleich bleibt.
// Die Zusagen (YES) sind bewusst lang: Die Auswahl zieht genau einmal aus dem Wochen-Zufall, egal wie
// viele Varianten es gibt – mehr Varianten ändern nur den Text, nie Geld, Stimmung oder Tabellen.
import { tr } from '../core/i18n.js';

export const SHIFT_JOBS = ['Pflegekraft', 'Schichtarbeiter', 'Busfahrer', 'Bäcker', 'Lagerist', 'Paketbote'];
export const TRAVEL_JOBS = ['Elektriker', 'Dachdecker', 'Versicherungsmakler', 'IT-Admin'];

export const YES = tr(
  [
    'Bin dabei!',
    'Klar. Wer bringt die Bälle?',
    'Dabei, komme mit dem Rad.',
    'Jo. Hat jemand noch Stutzen für mich?',
    'Bin da. Diesmal auch pünktlich, versprochen.',
    'Safe dabei.',
    'Komme, aber nur wenn ich nicht wieder ins Tor muss.',
    'Bin dabei, bringe Kuchen von Oma mit.',
    'Dabei. Wer holt mich ab?',
    'Logo. Hab extra die Grillparty abgesagt.',
    'Bin am Start. Die neuen Schuhe wollen eingelaufen werden.',
    'Dabei, wenn meine Frau nicht doch noch was plant.',
    'Jawoll.',
    'Komme. Brauche Bewegung nach dem Wochenende.',
    'Bin dabei, bringe die Kiste Wasser mit.',
    'Klar, wann ist Treffpunkt?',
    'Dabei. Aber ich spiele nicht links.',
    'Bin da, hab sogar geschlafen diesmal.',
    'Läuft. Bin dabei.',
    'Komme direkt vom Bäcker, bringe Brötchen mit.',
    'Dabei! Letzte Woche war ja nix.',
    'Wenn der Rasen gemäht ist, bin ich da. Und auch sonst.',
    'Bin am Platz, wer hat den Schlüssel für den Geräteraum?',
    'Dabei. Schiri bitte nicht wieder der vom letzten Mal.',
    'Komme. Die Wade hält, glaube ich.',
    'Bin da, wenn jemand die Eckfahnen findet.',
    'Klar. Ich bring die Wurst für danach mit.',
    'Dabei, aber um sechs muss ich zum Fußballgucken daheim sein.',
    'Bin dabei, solange keiner Laufen sagt.',
    'Zusage. Hab sogar die Schienbeinschoner gefunden.',
    'Komme, aber ich stell mich ins Mittelfeld, da wird weniger gerannt.',
    'Passt. Ich fahr mit dem Nachbarn, falls der nicht verschläft.',
    'Bin am Start, Auto steht schon vollgetankt vor der Tür.',
    'Dabei. Wehe, es regnet wieder quer.',
    'Ja, ich komm. Die Couch kann warten.',
    'Mach ich. Hab die Trikots schon in der Tasche.',
    'Bin da, bringe Kaffee in der Thermoskanne mit.',
    'Dabei, aber nur, wenn keiner wieder von Taktik anfängt.',
    'Mir gehen die Ausreden aus. Komme.',
    'Natürlich. Wann sonst komm ich mal raus.',
    'Bin dabei, die Knie sagen zwar nein, aber egal.',
    'Klappt. Der Kleine ist bei der Oma.',
    'Komme, wenn ich den Parkplatz am Sportheim finde.',
    'Dabei! Hab die ganze Woche nur dafür gelebt.',
    'Bin da. Und diesmal wärm ich mich sogar auf.',
    'Zusage, aber ich geh früh duschen.',
    'Passt, ich bring die Pumpe für die Bälle mit.',
    'Komme. Bitte nicht wieder auf die Zehn stellen.',
    'Bin dabei, solange es danach was Warmes gibt.',
    'Dabei, ich hab frei bekommen. Frag nicht wie.',
    'Jo, komme. Muss nur noch die Stutzen waschen.',
    'Klar bin ich da, wo sonst soll ich sonntags hin?',
    'Bin dabei, wenn jemand die Getränkekiste schleppt.',
    'Komme. Der Wecker ist gestellt, zweimal sogar.',
    'Dabei, ich nehm den Bus und hoffe aufs Beste.',
    'Klar, ich bin da. Schlimmer als letzte Woche geht’s eh nicht.',
    'Bin am Start, hab den Ball vom Sohnemann geklaut.',
    'Dabei. Aber bitte nicht um 9 aufwärmen.',
    'Komme, wenn die Dusche warm ist. Sonst auch.',
    'Passt, ich bring Sportgetränk mit. Das Pulver von 2019.',
    'Bin da. Die Tasche ist gepackt, der Kopf noch nicht.',
    'Dabei, aber ich fahr nicht wieder mit dem Vorstand.',
    'Mach ich. Muss nur noch den Hund abgeben.',
    'Komme direkt von der Nachtschicht, schlaf ich halt im Tor.',
    'Klar. Wenn ihr die Kreide fürs Feld habt.',
    'Bin dabei, die Schuhe sind frisch geputzt. Hält bis zur 5. Minute.',
    'Dabei, aber ich muss um vier die Schwiegermutter abholen.',
    'Komme. Hab mir extra eine neue Stirnbinde gekauft.',
    'Natürlich bin ich da. Wer sonst hält den Laden zusammen?',
    'Bin dabei, solange der Platz nicht wieder ein Acker ist.',
    'Jo, passt. Die Frau hat gesagt: Geh endlich!',
    'Zusage. Aber heute treff ich mal das Tor, versprochen.',
    'Dabei, mein Bruder fährt, ich muss nur früh aufstehen.',
    'Komme gern. Hab nur noch die Waschmaschine im Kopf.',
    'Bin am Start. Wer hat Tape für die Stutzen?',
    'Klar, Sonntag ist Fußballtag. Der Rest ist Beilage.',
    'Dabei. Hab die Taktik der letzten Woche schon vergessen.',
    'Komme, hab sogar die Eckfahne vom Platz gerettet.',
    'Bin da, aber ich bring meine eigene Trinkflasche mit.',
    'Passt. Ich organisier die Fahrgemeinschaft ab dem Marktplatz.',
    'Dabei, aber ich spiel nur, wenn ich nicht ins Tor muss. Wieder.',
    'Klappt. Hab die Gartenarbeit auf nächste Woche verschoben.',
    'Bin dabei, wenn’s danach Currywurst gibt.',
    'Komme. Das Handy bleibt im Auto, versprochen.',
    'Dabei! Ich hab sogar einen neuen Ball dabei. Also fast neu.',
    'Zusage. Der Rücken meldet sich ab, ich nicht.',
    'Bin da, ich bring Kuchen. Frag nicht, von wem.',
    'Klar, solange wir nicht wieder in der prallen Sonne stehen.',
    'Dabei. Wer kümmert sich um die Trikots, ich war letztes Mal dran.',
    'Komme direkt vom Frühschoppen. Nur ein Bier, ehrlich.',
    'Passt. Ich bring Pflaster mit, für alle Fälle.',
    'Bin dabei. Und diesmal nehm ich die Elfmeter.',
    'Dabei, auch wenn die Waden schon Montag spüren, was kommt.',
    'Komme, hab frei und nichts Besseres vor.',
    'Jawohl, die Stutzen sind schon gewaschen.',
    'Bin am Platz, bring die Eckfahnen gleich mit.',
    'Dabei. Der Nachbar leiht mir seinen Anhänger für die Tore.',
    'Klar. Wann gibt’s endlich neue Netze?',
    'Komme, ich hab mir extra einen Wecker mit Anpfiff-Ton gestellt.',
    'Zusage, bringe Kaffee und kalte Frikadellen mit.',
    'Dabei. Hoffentlich spielen wir diesmal gegen elf Mann.',
    'Bin da, die Kondition kommt irgendwann nach.',
    'Klar, ich komme. Bei mir zuhause ist eh Chaos.',
    'Bin dabei. Haben wir noch das Trikot mit der Zwölf?',
    'Komme, ich hab mir sogar die Haare dafür gemacht.',
    'Dabei, wenn mich jemand vom Bahnhof abholt.',
    'Passt. Das Auto springt hoffentlich an.',
    'Bin am Start, ich hab Hunger auf Grillwurst und Tore.',
    'Ja, ich bin dabei. Auch wenn ich es morgen bereue.',
    'Komme. Die Ausrede vom letzten Mal ist verbraucht.',
    'Dabei, aber ich lauf nur, wenn der Ball in der Nähe ist.',
    'Logo, Sonntag ist heilig. Zumindest bis zum Abpfiff.',
  ],
  [
    'I’m in!',
    'Sure. Who’s bringing the balls?',
    'In, coming on the bike.',
    'Yep. Anyone got spare socks for me?',
    'I’ll be there. On time this time, promise.',
    'Definitely in.',
    'Coming, but only if I don’t have to go in goal again.',
    'I’m in, bringing Grandma’s cake.',
    'In. Who’s picking me up?',
    'Of course. Cancelled the barbecue for it.',
    'I’m on. Got new boots to break in.',
    'In, unless the wife has other plans.',
    'Yessir.',
    'Coming. Need to move after the weekend.',
    'I’m in, bringing a crate of water.',
    'Sure, what time do we meet?',
    'In. But I’m not playing on the left.',
    'I’ll be there, even slept this time.',
    'All good. I’m in.',
    'Coming straight from the bakery, bringing rolls.',
    'In! Last week was a write-off.',
    'If the grass is cut, I’m there. And if not, too.',
    'I’m at the pitch, who has the key to the kit room?',
    'In. Just not the same ref as last time, please.',
    'Coming. The calf is holding up, I think.',
    'I’m there, if someone finds the corner flags.',
    'Sure. I’ll bring the sausages for afterwards.',
    'In, but I’ve got to be home by six for the telly football.',
    'I’m in, as long as nobody says running.',
    'Count me in. Even found my shin pads.',
    'Coming, but I’m standing in midfield, less running there.',
    'Fine. I’m getting a lift with my neighbour, if he doesn’t oversleep.',
    'I’m on, car’s already out front with a full tank.',
    'In. It had better not rain sideways again.',
    'Yes, I’ll come. The sofa can wait.',
    'Will do. Shirts are already in my bag.',
    'I’m there, bringing coffee in a flask.',
    'In, but only if nobody starts on tactics again.',
    'I’ve run out of excuses. Coming.',
    'Of course. When else do I get out of the house.',
    'I’m in. The knees say no, but never mind.',
    'Works. The little one’s at Grandma’s.',
    'Coming, if I can find a spot at the clubhouse.',
    'In! Lived for this all week.',
    'I’ll be there. And this time I’ll even warm up.',
    'Count me in, but I’m showering early.',
    'Fine, I’ll bring the pump for the balls.',
    'Coming. Please don’t put me on the ten again.',
    'I’m in, as long as there’s something hot afterwards.',
    'In, got the day off. Don’t ask how.',
    'Yep, coming. Just got to wash the socks.',
    'Course I’m there, where else would I go on a Sunday?',
    'In, if someone carries the drinks crate.',
    'Coming. Alarm is set, twice even.',
    'In, taking the bus and hoping for the best.',
    'Sure, I’ll be there. Can’t be worse than last week.',
    'I’m on, nicked my son’s ball.',
    'In. But please, no warm-up at nine.',
    'Coming if the shower’s warm. And if not.',
    'Fine, bringing sports drink. The powder from 2019.',
    'I’m there. Bag is packed, head isn’t.',
    'In, but I’m not riding with the committee again.',
    'Will do. Just need to drop the dog off.',
    'Coming straight from nights, I’ll sleep in goal.',
    'Sure. If you’ve got the chalk for the lines.',
    'In, boots freshly cleaned. Lasts until minute five.',
    'In, but I’ve got to fetch the mother-in-law at four.',
    'Coming. Bought a new headband just for this.',
    'Course I’m there. Who else holds this lot together?',
    'In, as long as the pitch isn’t a ploughed field again.',
    'Yep, fine. The missus said: go already!',
    'Count me in. And today I’ll hit the target, promise.',
    'In, my brother’s driving, I just have to get up early.',
    'Happy to come. Still got the washing machine on my mind.',
    'I’m on. Anyone got tape for the socks?',
    'Sure, Sunday is football day. The rest is a side dish.',
    'In. Already forgot last week’s tactics.',
    'Coming, even rescued the corner flag from the pitch.',
    'I’m there, but I’m bringing my own bottle.',
    'Fine. I’ll organise the lift share from the market square.',
    'In, but only if I’m not in goal. Again.',
    'Works. Moved the gardening to next week.',
    'In, if there’s currywurst afterwards.',
    'Coming. Phone stays in the car, promise.',
    'In! Even bringing a new ball. Well, nearly new.',
    'Yes. The back is signing off, I’m not.',
    'I’m there, bringing cake. Don’t ask who made it.',
    'Sure, as long as we’re not in the blazing sun again.',
    'In. Who’s doing the shirts, I did them last time.',
    'Coming straight from the pub. Just the one pint, honest.',
    'Fine. Bringing plasters, just in case.',
    'I’m in. And this time I’m taking the penalties.',
    'In, even though my calves already feel Monday coming.',
    'Coming, got the day off and nothing better to do.',
    'Right you are, socks are already washed.',
    'I’ll be at the pitch, bringing the corner flags too.',
    'In. The neighbour is lending me his trailer for the goals.',
    'Sure. When do we finally get new nets?',
    'Coming, set an alarm with a whistle sound.',
    'Yes, bringing coffee and cold meatballs.',
    'In. Hopefully we play against eleven men this time.',
    'I’m there, fitness will catch up eventually.',
    'Sure, I’ll come. It’s chaos at home anyway.',
    'In. Do we still have the shirt with the twelve?',
    'Coming, even did my hair for it.',
    'In, if someone picks me up from the station.',
    'Fine. The car will hopefully start.',
    'I’m on, hungry for bratwurst and goals.',
    'Yes, I’m in. Even if I regret it tomorrow.',
    'Coming. Last time’s excuse is used up.',
    'In, but I only run if the ball is nearby.',
    'Course, Sunday is sacred. At least until the final whistle.',
  ],
);

const NO_BY_JOB = tr(
  {
    shift: ['Hab Spätschicht, sorry.', 'Muss Sonntag Dienst schieben.', 'Frühschicht bis 14 Uhr, klappt nicht.'],
    travel: ['Bin auf Montage in Dortmund.', 'Muss zum Kunden, sorry Leute.', 'Bin erst Montag wieder da.'],
    Student: ['Klausurphase. Leider.', 'Muss Hausarbeit schreiben (angeblich).'],
    Frührentner: ['Kegeln mit dem Verein, das geht vor.', 'Bin mit meiner Frau im Harz.'],
  },
  {
    shift: ['Late shift, sorry.', 'Working Sunday.', 'Early shift until 2pm, can’t make it.'],
    travel: ['I’m on a job in Dortmund.', 'Got to see a customer, sorry lads.', 'Not back until Monday.'],
    Student: ['Exam season. Sadly.', 'Got an essay to write (apparently).'],
    Frührentner: ['Bowling club, that comes first.', 'Away in the Harz with the wife.'],
  },
);

export const NO_GENERIC = tr(
  [
    'Hochzeit von der Cousine.',
    'Kinder haben Geburtstag, keine Chance.',
    'Bin krank. Wirklich!',
    'Schwiegereltern kommen. Mehr sag ich nicht.',
    'Umzug von nem Kumpel, hab zugesagt.',
    'Rücken.',
    'Oma hat 80. Geburtstag.',
    'Bin beim Junggesellenabschied, Sonntag nicht einsatzfähig.',
    'Auto ist in der Werkstatt, komme nicht hin.',
    'Muss mit dem Hund zum Tierarzt.',
    'Hab meiner Freundin den Flohmarkt versprochen.',
    'Grippe. Die echte.',
    'Bin Trauzeuge, kann nicht.',
    'Wir streichen die Wohnung, keine Chance.',
    'Kommunion vom Patenkind.',
    'Hab mir beim Rasenmähen den Fuß vertreten. Ja, wirklich.',
  ],
  [
    'My cousin’s wedding.',
    'Kids’ birthday party, no chance.',
    'I’m ill. Really!',
    'The in-laws are coming. That’s all I’m saying.',
    'Helping a mate move house, promised him.',
    'My back.',
    'Grandma’s 80th birthday.',
    'Stag do on Saturday, won’t be fit on Sunday.',
    'Car’s in the garage, no way to get there.',
    'Taking the dog to the vet.',
    'Promised my girlfriend the flea market.',
    'Flu. The real one.',
    'Best man at a wedding, can’t.',
    'We’re painting the flat, no chance.',
    'Godchild’s first communion.',
    'Twisted my ankle mowing the lawn. Yes, really.',
  ],
);

export const LATE = tr(
  [
    'Komme zur zweiten Halbzeit, hab vorher noch Taufe.',
    'Schaffe es erst zur Pause, stellt mich auf die Bank.',
    'Bin später da, muss den Kleinen noch zum Handball bringen.',
    'Komme etwas später, der Bus fährt sonntags nur stündlich.',
    'Bin da, aber erst nach dem Frühstück bei den Schwiegereltern.',
    'Schaffe es knapp, fangt ohne mich an.',
    'Komme nach, muss noch den Transporter zurückbringen.',
    'Komme zur Halbzeit, vorher noch Schwimmkurs vom Kleinen.',
    'Bin später da, der Zug hat wieder Verspätung.',
    'Komme nach, muss erst noch das Auto vom Nachbarn anschieben.',
    'Schaffe es erst nach dem Mittagessen bei Mama.',
    'Bin spät dran, der Schlüssel ist weg. Fangt an.',
    'Komme in der 30. Minute, vorher muss ich zum Bäcker.',
    'Komme später, muss erst noch die Mülltonnen rausstellen.',
  ],
  [
    'I’ll come for the second half, got a christening first.',
    'Won’t make it until half-time, put me on the bench.',
    'I’ll be late, got to take the little one to handball first.',
    'I’ll be a bit late, the bus only runs hourly on Sundays.',
    'I’ll be there, but only after breakfast at the in-laws.',
    'Cutting it close, start without me.',
    'Coming later, got to return the van first.',
    'Coming at half-time, got the little one’s swimming lesson first.',
    'I’ll be late, the train’s delayed again.',
    'Coming later, got to push the neighbour’s car first.',
    'Won’t make it until after lunch at Mum’s.',
    'Running late, can’t find my keys. Start without me.',
    'Coming around the 30th minute, got to nip to the bakery first.',
    'Coming later, got to put the bins out first.',
  ],
);

// Ab Kreisliga A: Der elektronische Spielbericht ist vor dem Anpfiff zu – wer später kommt, spielt nicht.
export const LATE_STRICT = tr(
  [
    'Schaffe es nicht rechtzeitig zum Anpfiff, sorry. Spielt ohne mich.',
    'Komme zu spät, der Spielbericht ist dann schon zu.',
    'Taufe zieht sich, bin nicht vor dem Anpfiff da. Streicht mich aus dem Bericht.',
    'Der Bus fährt sonntags nur stündlich, ich komm zu spät. Tragt mich nicht ein.',
    'Muss erst den Kleinen zum Handball bringen, bin nicht pünktlich. Ohne mich.',
    'Zug hat Verspätung, bis zum Anpfiff schaffe ich es nicht. Dann darf ich eh nicht mehr rein.',
    'Schlüssel weg, Auto weg, Laune weg. Ich bin nicht rechtzeitig da.',
    'Bin beim Schwiegerelternfrühstück gefangen. Zum Anpfiff nicht da, also nicht im Bericht.',
    'Transporter muss noch zurück, ich komme nach dem Anpfiff. Schreibt mich bitte raus.',
    'Schaffe es nicht vor dem Anpfiff, nach Freigabe des Spielberichts ist eh zu. Viel Erfolg!',
    'Komme zu spät, Mülltonnen und so. Ich schaue von der Bande zu.',
    'Nicht pünktlich da, sorry. Ich bring dafür den Kasten für nachher mit.',
  ],
  [
    'Won’t make it in time for kick-off, sorry. Play without me.',
    'I’ll be too late, the match report will be closed by then.',
    'The christening is dragging on, I won’t be there before kick-off. Take me off the report.',
    'The bus only runs hourly on Sundays, I’ll be late. Don’t put me down.',
    'Got to take the little one to handball first, I won’t be on time. Count me out.',
    'Train’s delayed, I won’t make kick-off. They won’t let me on after that anyway.',
    'Keys gone, car gone, mood gone. I won’t be there in time.',
    'Stuck at breakfast with the in-laws. Not there for kick-off, so not on the report.',
    'Got to return the van, I’ll come after kick-off. Please take me off the sheet.',
    'Won’t make it before kick-off, and once the report is signed off that’s it. Good luck!',
    'Running late, bins and all that. I’ll watch from the touchline.',
    'Not there on time, sorry. I’ll bring the crate for afterwards though.',
  ],
);

export const INJURED = tr(
  ['Knie ist noch offen von letzter Woche. Setze aus.', 'Das Knie… nächste Woche wieder.', 'Die Wade macht zu. Lieber eine Woche Pause.', 'Physio sagt nein. Ich sag auch nein.'],
  ['Knee is still raw from last week. Sitting this one out.', 'The knee… back next week.', 'Calf is tight. Better take a week off.', 'Physio says no. I say no too.'],
);

export const NUDGE_YES = tr(
  ['Na gut, ich tausch die Schicht.', 'Okay okay, ich komm. Aber nur weil du es bist.', 'Überredet. Aber ich spiel nicht hinten!'],
  ['Fine, I’ll swap my shift.', 'Okay okay, I’ll come. But only because it’s you.', 'You’ve talked me into it. But I’m not playing at the back!'],
);
export const NUDGE_NO = tr(
  ['Geht echt nicht, sorry.', 'Nee, wirklich nicht. Nächste Woche!', 'Lass gut sein, ich kann nicht.'],
  ['Really can’t, sorry.', 'No, honestly not. Next week!', 'Leave it, I can’t.'],
);

export function noReasons(profession) {
  if (SHIFT_JOBS.includes(profession)) return NO_BY_JOB.shift;
  if (TRAVEL_JOBS.includes(profession)) return NO_BY_JOB.travel;
  if (profession.startsWith('Student')) return NO_BY_JOB.Student;
  return NO_BY_JOB[profession] ?? NO_GENERIC;
}

// Wie wahrscheinlich sagt jemand ab? Schichtarbeit & Montage machen's schwer.
export function absenceChance(profession) {
  if (SHIFT_JOBS.includes(profession)) return 0.28;
  if (TRAVEL_JOBS.includes(profession)) return 0.22;
  return 0.14;
}

// Gerüchteküche – woher man von neuen Leuten hört.
export const RUMOR_SOURCES = {
  ok: [
    (p) => tr(`${p.first} aus der Nachbarschaft kickt manchmal im Park mit. Soll ganz okay sein.`, `${p.first} from round the corner sometimes plays in the park. Supposed to be all right.`),
    (p) => tr(`Ein Arbeitskollege, ${p.first}, hätte wohl Lust auf Sonntags-Kick.`, `A colleague, ${p.first}, fancies a Sunday kickabout.`),
    (p) => tr(`${p.first} hat im Kiosk gefragt, ob noch jemand Leute sucht.`, `${p.first} asked at the corner shop if anyone needs players.`),
    (p) => tr(`Der Mitbewohner von einem aus der Gruppe, ${p.first}, würde gern mal mitspielen.`, `The flatmate of someone in the group, ${p.first}, would like a game.`),
  ],
  gut: [
    (p) => tr(`Beim Bäcker erzählen sie, ${p.name} sucht einen Verein – war früher mal in der B-Klasse.`, `At the bakery they say ${p.name} is looking for a club – used to play in League B.`),
    (p) => tr(`${p.name} hat beim Firmenlauf alle abgehängt. Kickt angeblich auch.`, `${p.name} left everyone behind at the company fun run. Apparently plays football too.`),
    (p) => tr(`${p.name} ist gerade hergezogen und fragt in der Nachbarschaftsgruppe nach einem Verein.`, `${p.name} has just moved here and is asking the neighbourhood group about a club.`),
    (p) => tr(`Beim Sommerfest der Kita hat ${p.name} beim Elfmeterschießen alles versenkt.`, `At the nursery summer fair ${p.name} scored every penalty.`),
  ],
  stark: [
    (p) => tr(`${p.name} ist neu im Viertel. Man hört, er war beim alten Verein Stammspieler.`, `${p.name} is new in the area. Word is he was a regular at his old club.`),
    (p) => tr(`Im Kiosk sagen sie, ${p.name} hat früher Bezirksliga gespielt.`, `At the corner shop they say ${p.name} used to play county league.`),
    (p) => tr(`${p.name} spielt dienstags Hallenfußball mit den Schichtleuten – und macht alle nass.`, `${p.name} plays indoor football with the shift workers on Tuesdays – and runs rings round them.`),
  ],
  dorfstar: [
    (p) => tr(`Im Vereinsheim flüstert man: ${p.name} hat Stress bei seinem Verein. Der trifft angeblich, wie er will.`, `They’re whispering at the clubhouse: ${p.name} has fallen out with his club. Supposedly scores at will.`),
    (p) => tr(`${p.name}? Den kennt hier jeder. Soll gerade vereinslos sein.`, `${p.name}? Everyone round here knows him. Supposed to be without a club right now.`),
  ],
  superstar: [(p) => tr(`Unglaublich, aber wahr: ${p.name} soll mal richtig hoch gespielt haben – und jetzt hier wohnen!`, `Unbelievable but true: ${p.name} is supposed to have played at a really high level – and now lives here!`)],
  legende: [(p) => tr(`GERÜCHT: Ein ehemaliger Profi ist ins Neubaugebiet gezogen. „${p.title}"? Im Supermarkt hat ihn jemand erkannt.`, `RUMOUR: a former pro has moved onto the new estate. "${p.title}"? Someone recognised him at the supermarket.`)],
};

export const JOIN_TEXT = tr(
  ['Bin dabei. Wann ist Training?', 'Okay, ich komm vorbei. Wer hat die Trikots?', 'Klingt gut. Gibt es danach Bier?'],
  ['I’m in. When’s training?', 'Okay, I’ll come along. Who has the shirts?', 'Sounds good. Is there beer afterwards?'],
);
export const DECLINE_TEXT = tr(
  {
    default: ['Danke, aber ich bleib bei meinen Jungs.', 'Sonntags ist Familientag, sorry.', 'Vielleicht nächste Saison.'],
    legende: ['Vielleicht nächste Saison. Erstmal ankommen.', 'Ich will einfach nur kicken – bei euch ist mir zu viel Trubel.'],
    superstar: ['Nur wenn ich um 15 Uhr wieder zu Hause bin. Ach, das klappt eh nicht.', 'Ich überleg es mir. Meldet euch nächste Woche nochmal.'],
  },
  {
    default: ['Thanks, but I’m staying with my lads.', 'Sunday is family day, sorry.', 'Maybe next season.'],
    legende: ['Maybe next season. Settling in first.', 'I just want to play – there’s too much fuss at your place.'],
    superstar: ['Only if I’m home by 3pm. Oh, that won’t work anyway.', 'I’ll think about it. Get back to me next week.'],
  },
);
export const FAREWELL = tr(
  ['Danke für alles, Männer. Man sieht sich im Vereinsheim.', 'War schön mit euch. Ich komm zum Sommerfest!'],
  ['Thanks for everything, lads. See you at the clubhouse.', 'It was great with you. I’ll come to the summer party!'],
);
